name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Install python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
          pip install mypy
          pip install twine
          pip install setuptools
          pip install coverage codecov
      - name: Run flake8
        run: flake8 .
      - name: Run mypy
        run: mypy .
      - name: Run tests
        run: |
          python tests/test_calculate.py
          python tests/test_countours.py
          python tests/test_draw.py
          python tests/test_xlsx.py
      - name: Run PyPi
        run: |
          python setup.py sdist
          python -m twine upload dist/* --username Kvasik --password .9SNR3zft3HX_Bb
      - name: Run cov
        run: |
          coverage run -m tests/test_calculate.py
          coverage run -m tests/test_countours.py
          coverage run -m python tests/test_draw.py
          coverage run -m python tests/test_xlsx.py
          coverage report -m tests/test_calculate.py
          coverage report -m tests/test_countours.py
          coverage report -m tests/test_draw.py
          coverage report -m tests/test_xlsx.py
      
   
